name: Test Install Script

on:
  push:
    paths:
      - 'install.sh'
      - '.github/workflows/test-install.yml'
      - 'packages/**'
      - 'config/**'
  pull_request:

jobs:
  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel git sudo
          useradd -m testuser || true
          echo "testuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
      - name: Run install.sh as testuser
        run: |
          sudo -u testuser bash install.sh

  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          dnf upgrade -y
          dnf install -y sudo git
          useradd -m testuser || true
          echo "testuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
      - name: Run install.sh as testuser
        run: |
          sudo -u testuser bash install.sh
